In [6]:
import pandas as pd

df_casas = pd.read_csv("../Output/casas.csv", low_memory=False)
df_poblacion = pd.read_csv("../Output/poblacion.csv")
df_rentas = pd.read_csv("../Output/rentas_espana_limpia.csv")

In [7]:
df_casas.head()

,ad_last_update,bath_num,condition,construct_date,energetic_certif,house_id,house_type,loc_city,loc_district,loc_full,loc_zone,m2_real,m2_useful,obtention_date,orientation,price,room_num
0,Anuncio actualizado el 27 de marzo,2.0,segunda mano/buen estado,NaN,no indicado,81717634,Casa o chalet independiente,Urcabustaiz,La iglesia,"La iglesia , Urcabustaiz , Zuya, Álava","Zuya, Álava",1000.0,172.0,2019-03-29,"norte, sur, este, oeste",310000.0,4.0
1,más de 5 meses sin actualizar,2.0,segunda mano/buen estado,1970-01-01 00:00:00.000002006,no indicado,29588074,Ático,Legutiano,"la Union Plazatxoa, 8","la Union Plazatxoa, 8 , Legutiano , Zuya, Álava","Zuya, Álava",86.0,NaN,2019-03-29,NaN,139000.0,3.0
2,más de 5 meses sin actualizar,3.0,segunda mano/buen estado,NaN,no indicado,37453116,Casa de pueblo,Aramaio,Calle Etxaguen s/n,"Calle Etxaguen s/n , Aramaio , Zuya, Álava","Zuya, Álava",3000.0,NaN,2019-03-29,NaN,480000.0,4.0
3,más de 5 meses sin actualizar,1.0,segunda mano/buen estado,NaN,en trámite,82568918,Casa de pueblo,Urcabustaiz,"CP 01449, 1449 CP","CP 01449, 1449 CP , Urcabustaiz , Zuya, Álava","Zuya, Álava",86.0,NaN,2019-03-29,NaN,150000.0,4.0
4,más de 5 meses sin actualizar,1.0,segunda mano/buen estado,NaN,no indicado,29135242,Piso,Urcabustaiz,"Calle Nueva Plaza, 9","Calle Nueva Plaza, 9 , Urcabustaiz , Zuya, Ál...","Zuya, Álava",76.0,74.0,2019-03-29,"sur, oeste",90000.0,2.0

In [8]:
df_poblacion.head()

          poblacion    source   valor  cod_provincia
0          Albacete  Empresas   26743              2
1  Alicante/Alacant  Empresas  138964              3
2           Almería  Empresas   42931              4
3       Araba/Álava  Empresas   19147              1
4          Asturias  Empresas   68688             33

In [9]:
df_rentas.head()

,Número de declaraciones,Renta bruta media,Renta disponible media,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de autoliquidación,Renta disponible,Municipio,Id Municipio
0,75867,23.037,19.415,1456012595,71236502,1747748989,71001490,203864325,1472973679,Jerez de la Frontera,11020
1,139685,24.956,20.590,2872080318,95447256,3486036496,131696823,478299401,2876132145,Córdoba,14021
2,107278,27.895,22.856,2348548998,127809334,2992558477,98352388,442317860,2451956604,Granada,18087
3,219677,25.180,20.980,4392190510,257940065,5531461016,208101984,714702889,4608791911,Málaga,29067
4,288039,28.019,22.822,6557221055,290595019,8070490996,292398468,1204652257,6573711090,Sevilla,41091