In [30]:
import pandas as pd

df_rentas = pd.read_csv("../Data_Raw/rentas_espanya.csv")

In [31]:
print(df_rentas.shape)

(33, 10)

In [32]:
df_rentas

,Unnamed: 0,Número de declaraciones,Renta bruta media,Renta disponible media,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de autoliquidación,Renta disponible
0,Jerez de la Frontera-11020,75.867,23.037,19.415,1.456.012.595,71.236.502,1.747.748.989,71.001.490,203.864.325,1.472.973.679
1,Córdoba-14021,139.685,24.956,20.590,2.872.080.318,95.447.256,3.486.036.496,131.696.823,478.299.401,2.876.132.145
2,Granada-18087,107.278,27.895,22.856,2.348.548.998,127.809.334,2.992.558.477,98.352.388,442.317.860,2.451.956.604
3,Málaga-29067,219.677,25.180,20.980,4.392.190.510,257.940.065,5.531.461.016,208.101.984,714.702.889,4.608.791.911
4,Sevilla-41091,288.039,28.019,22.822,6.557.221.055,290.595.019,8.070.490.996,292.398.468,1.204.652.257,6.573.711.090
5,Zaragoza-50297,362.307,27.294,22.358,8.161.132.827,298.238.043,9.888.942.023,383.888.444,1.404.736.690,8.100.578.959
6,Gijón-33024,137.440,26.261,21.830,2.965.968.434,160.740.720,3.609.304.098,133.538.005,475.550.817,3.000.317.718
7,Oviedo-33044,116.978,28.581,23.377,2.740.111.849,131.896.231,3.343.338.523,126.454.908,482.421.665,2.734.587.379
8,Palma de Mallorca-07040,183.485,28.973,23.568,3.972.910.715,132.418.940,5.316.085.246,189.437.312,802.397.269,4.324.364.117
9,Palmas de Gran Canaria Las-35016,151.711,27.694,22.682,3.308.234.034,117.423.610,4.201.481.710,149.391.083,611.148.054,3.441.145.211
10,Santa Cruz de Tenerife-38038,84.309,27.164,22.339,1.817.677.309,59.970.394,2.290.134.567,80.457.952,326.358.947,1.883.367.236
11,Santander-39075,85.228,28.233,23.199,1.933.974.315,73.275.839,2.406.268.494,81.046.593,348.119.994,1.977.183.255
12,Burgos-09059,103.140,26.415,21.902,2.308.231.412,67.572.101,2.724.474.088,106.773.599,358.767.799,2.259.014.478
13,Valladolid-47186,166.690,26.792,22.221,3.721.461.117,144.311.340,4.465.999.009,160.021.415,602.118.932,3.703.990.093
14,Badalona-08015,93.744,25.970,21.495,2.006.461.288,93.444.587,2.434.553.495,98.946.088,320.602.099,2.015.061.882
15,Barcelona-08019,825.322,36.050,28.514,21.829.363.261,898.912.520,29.752.870.873,932.987.451,5.288.012.713,23.533.074.379
16,Hospitalet de Llobregat L-08101,108.760,24.045,20.164,2.230.486.070,113.079.293,2.615.092.444,105.858.669,316.281.491,2.193.010.644
17,Sabadell-08187,93.946,27.691,22.654,2.132.307.645,111.091.032,2.601.489.551,106.762.497,366.579.042,2.128.206.926
18,Terrassa-08279,99.322,26.474,21.751,2.199.564.617,110.296.872,2.629.409.124,113.726.246,355.420.258,2.160.348.727
19,Coruña A-15030,131.428,28.055,22.803,3.018.209.634,104.850.923,3.687.155.708,129.548.536,560.820.322,2.996.946.847
20,Vigo-36057,141.190,25.871,21.343,3.032.565.731,107.450.437,3.652.705.353,140.669.084,498.683.293,3.013.445.966
21,Alcalá de Henares-28005,89.788,26.741,22.098,2.098.093.828,78.668.365,2.400.980.699,101.193.411,315.706.475,1.984.173.073
22,Alcobendas-28006,52.483,50.550,38.106,1.952.973.799,62.123.831,2.653.028.401,68.240.282,584.957.119,1.999.901.635
23,Getafe-28065,85.934,26.688,22.070,1.986.298.836,64.552.729,2.293.432.479,98.837.671,298.093.796,1.896.549.280
24,Madrid-28079,1.647.539,37.242,29.400,47.382.825.507,1.754.806.296,61.358.457.581,1.977.759.774,10.946.011.877,48.436.969.456
25,Móstoles-28092,94.034,23.596,19.853,1.955.741.557,70.001.574,2.218.781.502,96.582.103,255.431.675,1.866.858.712
26,Pozuelo de Alarcón-28115,43.256,72.993,53.428,2.192.617.585,75.166.853,3.157.402.856,65.915.165,780.487.765,2.311.098.776
27,Las Rozas-28127,47.809,50.286,38.258,1.887.397.371,77.416.388,2.404.146.386,76.780.520,498.381.562,1.829.077.671
28,Cartagena-30016,85.607,24.651,20.548,1.795.821.663,69.097.851,2.110.278.842,83.786.802,267.502.455,1.759.032.438
29,Murcia-30030,184.990,25.724,21.172,3.885.557.649,154.651.180,4.758.594.457,187.185.190,654.865.824,3.916.674.047
30,Alicante/Alacant-03014,133.309,26.389,21.613,2.859.315.251,93.156.447,3.517.847.852,129.661.318,507.133.669,2.881.212.058
31,Elche/Elx-03065,88.687,20.099,16.977,1.443.196.799,43.036.609,1.782.519.949,79.516.459,197.384.497,1.505.657.972
32,Valencia-46250,366.893,29.064,23.532,8.268.891.708,346.228.969,10.663.200.252,367.402.856,1.662.301.554,8.633.837.074

In [33]:
df_rentas.dtypes

Unnamed: 0                               object
Número de declaraciones                  object
Renta bruta media                       float64
Renta disponible media                  float64
Rentas del trabajo                       object
Rentas exentas                           object
Renta bruta                              object
Cotizaciones sociales a la SS            object
Cuota  resultante de autoliquidación     object
Renta disponible                         object
dtype: object

In [34]:
#Separamos el codigo del municipio del nombre del municipio
df_rentas = df_rentas.rename(columns={"Unnamed: 0": "municipio_cod"})
df_rentas["Municipio"] = df_rentas["municipio_cod"].str.rsplit("-", n=1).str[0]
df_rentas["Id Municipio"]   = df_rentas["municipio_cod"].str.rsplit("-", n=1).str[1]
df_rentas = df_rentas.drop(columns=["municipio_cod"])

In [35]:
df_rentas.head()

,Número de declaraciones,Renta bruta media,Renta disponible media,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de autoliquidación,Renta disponible,Municipio,Id Municipio
0,75.867,23.037,19.415,1.456.012.595,71.236.502,1.747.748.989,71.001.490,203.864.325,1.472.973.679,Jerez de la Frontera,11020
1,139.685,24.956,20.590,2.872.080.318,95.447.256,3.486.036.496,131.696.823,478.299.401,2.876.132.145,Córdoba,14021
2,107.278,27.895,22.856,2.348.548.998,127.809.334,2.992.558.477,98.352.388,442.317.860,2.451.956.604,Granada,18087
3,219.677,25.180,20.980,4.392.190.510,257.940.065,5.531.461.016,208.101.984,714.702.889,4.608.791.911,Málaga,29067
4,288.039,28.019,22.822,6.557.221.055,290.595.019,8.070.490.996,292.398.468,1.204.652.257,6.573.711.090,Sevilla,41091

In [36]:
#Eliminar puntos de miles y convertir las columnsa correspondientes a numérico
cols_numericas = [
    "Número de declaraciones", "Renta bruta media", "Renta disponible media",
    "Rentas del trabajo", "Rentas exentas", "Renta bruta",
    "Cotizaciones sociales a la SS", "Cuota  resultante de autoliquidación",
    "Renta disponible"
]

for col in cols_numericas:
    if df_rentas[col].dtype == object:
        df_rentas[col] = df_rentas[col].str.replace(".", "", regex=False)
    df_rentas[col] = pd.to_numeric(df_rentas[col], errors='coerce')

In [37]:
df_rentas["Número de declaraciones"] = df_rentas["Número de declaraciones"].astype(int) #cambiamos a int para evitar decimales en esta columna
print(df_rentas.shape)
print(df_rentas.dtypes)
df_rentas.head()

(33, 11)
Número de declaraciones                   int32
Renta bruta media                       float64
Renta disponible media                  float64
Rentas del trabajo                        int64
Rentas exentas                            int64
Renta bruta                               int64
Cotizaciones sociales a la SS             int64
Cuota  resultante de autoliquidación      int64
Renta disponible                          int64
Municipio                                object
Id Municipio                             object
dtype: object

,Número de declaraciones,Renta bruta media,Renta disponible media,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de autoliquidación,Renta disponible,Municipio,Id Municipio
0,75867,23.037,19.415,1456012595,71236502,1747748989,71001490,203864325,1472973679,Jerez de la Frontera,11020
1,139685,24.956,20.590,2872080318,95447256,3486036496,131696823,478299401,2876132145,Córdoba,14021
2,107278,27.895,22.856,2348548998,127809334,2992558477,98352388,442317860,2451956604,Granada,18087
3,219677,25.180,20.980,4392190510,257940065,5531461016,208101984,714702889,4608791911,Málaga,29067
4,288039,28.019,22.822,6557221055,290595019,8070490996,292398468,1204652257,6573711090,Sevilla,41091

In [38]:
print(f"Duplicados: {df_rentas.duplicated().sum()}")

Duplicados: 0

In [39]:
# Normalizamos el nombre de la columna para que coincida con el resto de los dataframes
df_rentas = df_rentas.rename(columns={'Municipio': 'provincia'})

In [40]:
df_rentas.head()

,Número de declaraciones,Renta bruta media,Renta disponible media,Rentas del trabajo,Rentas exentas,Renta bruta,Cotizaciones sociales a la SS,Cuota resultante de autoliquidación,Renta disponible,provincia,Id Municipio
0,75867,23.037,19.415,1456012595,71236502,1747748989,71001490,203864325,1472973679,Jerez de la Frontera,11020
1,139685,24.956,20.590,2872080318,95447256,3486036496,131696823,478299401,2876132145,Córdoba,14021
2,107278,27.895,22.856,2348548998,127809334,2992558477,98352388,442317860,2451956604,Granada,18087
3,219677,25.180,20.980,4392190510,257940065,5531461016,208101984,714702889,4608791911,Málaga,29067
4,288039,28.019,22.822,6557221055,290595019,8070490996,292398468,1204652257,6573711090,Sevilla,41091

In [41]:
df_rentas['provincia'].unique()

array(['Jerez de la Frontera', 'Córdoba', 'Granada', 'Málaga', 'Sevilla',
       'Zaragoza', 'Gijón', 'Oviedo', 'Palma de Mallorca',
       'Palmas de Gran Canaria Las', 'Santa Cruz de Tenerife',
       'Santander', 'Burgos', 'Valladolid', 'Badalona', 'Barcelona',
       'Hospitalet de Llobregat L', 'Sabadell', 'Terrassa', 'Coruña A',
       'Vigo', 'Alcalá de Henares', 'Alcobendas', 'Getafe', 'Madrid',
       'Móstoles', 'Pozuelo de Alarcón', 'Las Rozas', 'Cartagena',
       'Murcia', 'Alicante/Alacant', 'Elche/Elx', 'Valencia'],
      dtype=object)

In [42]:
import os

# Exportar a CSV
df_rentas.to_csv(os.path.join("../Output/rentas_espana_limpia.csv"), index=False)

print("✅ Archivo guardado en: Pre - Proyecto/Output/rentas_espana_limpia.csv")

✅ Archivo guardado en: Pre - Proyecto/Output/rentas_espana_limpia.csv